spring.application.name=SpringOauth2

#get the credientials from google cloud console
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=


spring.security.oauth2.client.registration.github.client-id=Ov23libUdydhOj1GrLpa
spring.security.oauth2.client.registration.github.client-secret=2d373165bb25b32e4ebeb0288064acf152e32172